import os

BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_SECRET = os.getenv("BINANCE_SECRET")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

FIREBASE_URL = os.getenv("FIREBASE_URL")

BASE_URL = os.getenv("BASE_URL", "http://localhost:8000")

MAX_DAILY_LOSS = float(os.getenv("MAX_DAILY_LOSS", 5))  # USD
MAX_CONSECUTIVE_LOSS = int(os.getenv("MAX_CONSECUTIVE_LOSS", 3))
BASE_RISK = float(os.getenv("BASE_RISK", 1))  # % per trade
MIN_RISK = 0.3
MAX_RISK = 2

PAIRS = [
    "BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT",
    "SUIUSDT","ADAUSDT","LTCUSDT","LINKUSDT","BCHUSDT",
    "DOGEUSDT","TRXUSDT","AVAXUSDT","XLMUSDT","TAOUSDT",
    "XAUUSDT","HYPEUSDT","XMRUSDT","XAGUSDT","ZECUSDT",
    "ENJUSDT","FILUSDT","AAVEUSDT","TONUSDT","ETCUSDT",
    "ATOMUSDT","DASHUSDT","QNTUSDT","MANAUSDT","ZENUSDT"
]